#ifndef CONF_TAREA_1
#define CONF_TAREA_1

//Logging Level
#define LOG_CONF_LEVEL_6LOWPAN  LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_TCPIP    LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_IPV6     LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_RPL      LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAC      LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_FRAMER   LOG_LEVEL_NONE

//Configuration Parameters
#define QUEBUF_CONF_NUM 4
#define NBR_TABLE_CONF_MAX_NEIGHBORS 25
#define UIP_CONF_BUFFER_SIZE 240
#define NETSTACK_MAX_ROUTE_ENTRIES 30
#define SICSLOWPAN_CONF_FRAG 1


#define WITH_SERVER_REPLY 1
#define UDP_PORT 5678
#define USABLE_RADIO_CHANNEL 16

#define SEND_INTERVAL (3*CLOCK_SECOND)

#endif // CONF_TAREA_1

